name: Email sending now
on:
  push:
    paths-ignore:
      # - '.github/*'
    branches:
    - main
    
jobs:
  setup-build-publish:
    name: send test email
    runs-on: ubuntu-latest

    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Specify connection via URL (replaces server_address, server_port, secure,
        # username and password)
        #
        # Format:
        #
        #  * smtp://user:password@server:port
        #  * smtp+starttls://user:password@server:port
        connection_url: ${{secrets.MAIL_CONNECTION}}
        # Required mail server address if not connection_url:
        server_address: smtp.gmail.com
        # Server port, default 25:
        server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: femi.adebayo@simplifysynergy.com,ayodimeji.fasina@simplifysynergy.com
        # Required sender full name (address can be skipped):
        from: Simplify DevOps # <user@example.com>
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        html_body: file://README.md
        # Optional carbon copy recipients:
        cc: scopiocity@yahoo.com,kazeem.akinrinde@simplifysynergy.com
        # Optional blind carbon copy recipients:
        bcc: olorunfemi15@gmail.com
        # Optional recipient of the email response:
        reply_to: femi.adebayo@simplifysynergy.com
        # Optional Message ID this message is replying to:
        in_reply_to: <femi.adebayo@simplifysynergy.com>
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: attachments.zip,git.diff,./dist/static/*.js
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: normal
